Update code-comment-cheker.yml
asd

diff --git a/.github/workflows/code-comment-cheker.yml b/.github/workflows/code-comment-cheker.yml
--- a/.github/workflows/code-comment-cheker.yml
+++ b/.github/workflows/code-comment-cheker.yml
@@ -25,8 +25,13 @@ jobs:
 
       - name: Calculate comment percentage
         run: |
-          total=$(cloc --exclude-dir=node_modules --csv --quiet . | awk -F, 'NR==2{print $2}')
-          comment=$(cloc --exclude-dir=node_modules --csv --quiet . | awk -F, 'NR==2{print $4}')
+          cloc_output=$(cloc --exclude-dir=node_modules --csv --quiet .)
+          total=$(echo "$cloc_output" | awk -F, 'NR==2{print $2}')
+          comment=$(echo "$cloc_output" | awk -F, 'NR==2{print $4}')
+          if [ "$total" -eq 0 ]; then
+            echo "Total lines of code is zero. Cannot calculate percentage."
+            exit 1
+          fi
           percentage=$(awk "BEGIN { pc=100*${comment}/${total}; i=int(pc); print (pc-i<0.5)?i:i+1 }")
           echo "Percentage of commented lines: $percentage%"
 
